### ISSUE TITLE
Disable automatic validating by default

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/validating#2]
I'd appreciate if we could disable automatic validating by default until we've resolve the memory consumption issues with the validator.

WDYT?

**Comment by danyill** [comment]
@JakobVogelsang I know it's not a great solution but would you accept a PR along these lines?

It is interesting, this might be a (not very good) example case for "per-plugin configurability" option with OpenSCD that one could set on a distribution basis.

**Comment by JakobVogelsang** [comment]
Yes sure let's do that. Sorry for the time we had not had a solution so far.
